package leetcode;

/**
 * @description: You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.
 * <p>
 * Return the minimum number of steps to make the given string empty.
 * <p>
 * A string is a subsequence of a given string if it is generated by deleting some characters of a given string without changing its order. Note that a subsequence does not necessarily need to be contiguous.
 * <p>
 * A string is called palindrome if is one that reads the same backward as well as forward.
 * @author: LISHUAI
 * @createDate: 2022/6/8 19:07
 * @version: 1.0
 */

public class LeetCode_1332 {

    public static int removePalindromeSub(String s) {
        int len = s.length();
        for (int i = 0; i < len; i++) {
            if (s.charAt(len - i - 1) != s.charAt(i)) {
                return 2;
            }
        }
        return 1;
    }
}
