package leetcode;

/**
 * @description: You are given two strings s and t.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Return the letter that was added to t.
 * @author: LISHUAI
 * @createDate: 2022/2/7 18:57
 * @version: 1.0
 */

public class LeetCode_389 {

    public static char findTheDifference(String s, String t) {

        char ansChar = 0;

        byte[] sBytes = s.getBytes();
        byte[] tBytes = t.getBytes();

        for (int i : sBytes) {

            ansChar ^= i;
        }

        for (int i : tBytes) {

            ansChar ^= i;
        }
        return (char) ansChar;
    }

    public static char findTheDifference_02(String s, String t) {

        char ansChar = 0;

        for (int i = 0; i < s.length(); i++) {

            ansChar ^= s.charAt(i);
        }

        for (int i = 0; i < t.length(); i++) {

            ansChar ^= t.charAt(i);
        }
        return (char) ansChar;
    }
}
